### ISSUE TITLE
Milestone: Commands cleanup

### ISSUE THREAD

**Issue by TptMike** [Everneth/EMI-RP#11]
Commands are a mess. Some commands need Strings moved to the final argument in the method signature (e.g.: Guild names should support more than one word). All commands need command completion support added as well as Command Replacement (e.g. guild color selection).

- [ ] Add `@Description()` to all command methods
- [ ] Add `@Syntax()` to all command methods
- [ ] Fix parameters in guild creation command
- [ ] Add CommandCompletion to all commands
- [ ] Register command replacement with the guild creation command to use a predefined list of colors to conform data being stored into the database and subsequently rendered into badges on the web app
- [ ] Add/Register an RP help command to list all available commands to staff and/or guilds
